package com.myspring.starbucks.mapper;

import com.myspring.starbucks.model.Order;
import com.myspring.starbucks.model.OrderExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    @Delete({
        "delete from t_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    Long insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    List<Order> selectByExampleWithRowbounds(OrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    @Select({
        "select",
        "id, create_time, update_time, customer, state,items",
        "from t_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.myspring.starbucks.mapper.OrderMapper.BaseResultMap")
    Order selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    @Update({
        "update t_order",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "customer = #{customer,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Order record);

    @Select({
            " SELECT ",
            " o.*,c.id cid,c.create_time cctime,c.update_time cutime,c.name,c.price ",
            " FROM ",
            " t_order o ",
            " LEFT JOIN t_order_coffee ocm ON o.id = ocm.coffee_order_id ",
            " LEFT JOIN t_coffee c ON ocm.items_id = c.id",
            " WHERE o.id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.myspring.starbucks.mapper.OrderMapper.NewResultMap")
    Order queryOrderById(Long id);
}