package com.myspring.starbucks.mapper;

import com.myspring.starbucks.model.OrderCoffee;
import com.myspring.starbucks.model.OrderCoffeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface OrderCoffeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    long countByExample(OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    int deleteByExample(OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    @Insert({
        "insert into t_order_coffee (coffee_order_id, items_id)",
        "values (#{coffeeOrderId,jdbcType=BIGINT}, #{itemsId,jdbcType=BIGINT})"
    })
    int insert(OrderCoffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    int insertSelective(OrderCoffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    List<OrderCoffee> selectByExampleWithRowbounds(OrderCoffeeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    List<OrderCoffee> selectByExample(OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") OrderCoffee record, @Param("example") OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_coffee
     *
     * @mbg.generated Tue Jun 16 21:41:08 GMT+08:00 2020
     */
    int updateByExample(@Param("record") OrderCoffee record, @Param("example") OrderCoffeeExample example);
}